using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EulerProblem2
{
    /*
    Problem: 

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    */
    class Program
    {
        static void Main(string[] args)
        {
            int fib1 = 1;
            int fib2 = 2;
            int temp = 0;
            int sum = 0;
            while (fib1 < 4000000)
            {
                if (fib1 % 2 == 0)
                {
                    sum = sum + fib1;
                }
                temp = fib1;
                fib1 = fib2;
                fib2 = temp + fib2;
            }
            Console.WriteLine(sum);
            //answer = 4613732
            //correct!
        }
    }
}
